### ISSUE TITLE
Should we keep technical vocabulary in english?

### ISSUE THREAD

**Issue by FFY00** [dlang-tour/portuguese#2]
I am starting the translation. I have translated most of the technical jargon to portuguese but this makes it somewhat unreadable. Programming has a really close knit with the english language so in portuguese we don't usually translate things like `high level`, at least the people I talk to. I don't think there's any need to translate literally everything due to this close relationship.

What do you think @wilzbach?

It may also be worth listening to the opinion of some portuguese users.
@ljmf00 @Ev1lbl0w @BGameiro76

**Comment by wilzbach** [comment]
I can't really help you here a I don't speak Portuguese, but from my experience translating the tour to other languages, I encountered similar problems.
For example, compiler can be translated to German, but it's such a common word in programming that we decided not to. However, we did try to be consistent and created a small wiki page which such words and the translation we took. I also often looked at a relevant Wikipedia article to check what words they use. Sometimes it helped.

**Comment by ljmf00** [comment]
I'm here to help you in everything you need for the translation process and also review changes as a language reviewer. I can take a look to the changes and propose things to improve it. :)

**Comment by FFY00** [comment]
Yes, I am checking Wikipedia too but they no longer support european portuguese. Somewhere in the past few years they decided to merge the european portuguese articles with to their brazilian portuguese version.
td;dr: "Portuguese" in Wikipedia is brasilian portuguese, they don't support european portuguese anymore.

I am gonna try to make it easy to read by the average person but still make it sane for the rest of us.

**Comment by ljmf00** [comment]
This question is a bit subjective, just because you really need to know the difference between imported foreignisms words and the proper translation for that word. Also, you may consider some specific technical jargon for that subject, but in my opinion, you should try to translate everything to plain portuguese, to be more clear and direct on what you want to say, except that really technical ones, which are used universally for every languages. For a good reference, check out some other languages in @dlang-tour group.

**Comment by FFY00** [comment]
Not related
@wilzbach I can't access the repository settings anymore. Was this intentional or was I never supposed to have that access? I want to mark the `master` branch as protected and force reviews before merging pull requests. I remember I had access because I needed to manually enable the issue tracker.

**Comment by wilzbach** [comment]
> Not related

So open a new issue? :P 

> @wilzbach I can't access the repository settings anymore.

You could never do that.

> Was this intentional or was I never supposed to have that access?

Intentional. It helps to keep all repositories to behave the same, have branch protection, required CI checks and web hooks to the dtour-bot (and so far we haven't encountered an instance where admin access was required by the translators.).

> I want to mark the master branch as protected and force reviews before merging pull requests.

That's the current setting:

![image](https://user-images.githubusercontent.com/4370550/43615275-26e61e10-96b7-11e8-9853-653a546190a4.png)

I didn't set the "Require reviews" check because I wasn't sure whether you will find enough reviewers.
So you want me to set it? (in my experience (here and at dlang-community) making this not required helps when you e.g. just want to get a typo fix deployed and don't want to wait a couple of days for this and you can somewhat trust the team to wait for reviews on bigger changes.)

> I remember I had access because I needed to manually enable the issue tracker.

Weird. The issue tracker should have been enabled by default. Maybe you are confusing things?

**Comment by FFY00** [comment]
With all the projects I contribute to, I am probably confusing things :grimacing:. Sorry for the hassle.

**Comment by FFY00** [comment]
@ljmf00 this makes things unreadable. It won't be more clear or direct because we just don't talk like that, at least nobody I know does.

Some examples:
  * `array` -> ?
  * `imports` -> `importações`??
  * `cast` -> ?
  * `string` -> `texto`???
  * `assert` -> `acertar`??
  * `pointers` -> `apontadores`????
  * `flow` -> `fluxo`??
  * `delegate` -> `delegador`??
  * ...

Do you see what I mean?

**Comment by rsubtil** [comment]
From my experience with translating technical terms to Portuguese, it really is hard to find a balance between what to translate and to what not :wink:

What I ended up doing was the following: if the term **had** a verb/conjugation, I would translate **only** the verb. For example: _pointers_. Since you can write statements like "this variable points to adress X...", I would translate the conjugation _points_. However, if the statement is like "We declare a pointer to...", I wouldn't touch the word _pointer_.

It isn't a general solution either, but it was the one I found more appealing when I was involved in translating projects.

**Comment by FFY00** [comment]
See #3 to see exactly what I mean. That is how I would like it to be translated.

**Comment by ljmf00** [comment]
@FFY00 Thats the thing, for me and for almost all people that understand well english and programming related stuff, you should keep that techinal jargons for a better understanding and universally. I know some people that translate everything into portuguese but some times not in a good way, unfortunately.

**Comment by FFY00** [comment]
That's what I have been saying. And for most things there's not a good way to translate them, just the least bad one, which for me it's not good enough.

**Comment by FFY00** [comment]
I am closing because #4 was approved.

Some final thoughts on the issue.
I don't mind translating everything to portuguese as long as we manage to find good/decent translations for the technical vocabulary. If we do find decent translations for some of this words we cannot use them until every single word is properly translated as the style wouldn't be consistent (some technical jargon would be translated and some wouldn't, this isn't consistent).

Also, don't mind my bad english in this comment as I am on a timer.
